FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo build-essential git cmake ninja-build pkg-config python3 python3-venv python3-pip \
    binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf gdb-multiarch \
    qemu-system-misc qemu-user qemu-user-static make vim less verilator gdb-multiarch \