services:
  # Lean development environment for SQL practice
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - postgres_data:/var/lib/postgresql/data
    working_dir: /workspace
    environment:
      - POSTGRES_DB=sql_practice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 10 &&
        cd /workspace &&
        ./scripts/setup-database.sh &&
        tail -f /dev/null
      "
    stdin_open: true
    tty: true

  # Demo runner - runs specific concepts
  demo:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - POSTGRES_DB=sql_practice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - dev
    network_mode: "service:dev"
    entrypoint: ["bash", "/workspace/scripts/demo.sh"]

volumes:
  postgres_data:
