services:
  # Development environment with full toolchain
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: development
    volumes:
      - .:/workspace
      - /workspace/.devcontainer  # Exclude devcontainer from sync
      - /workspace/build          # Exclude build artifacts
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    
  # Demo environment - minimal for running concepts
  demo:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: demo
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
    
  # Test runner - runs tests and exits (always clean build)
  test:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: demo
    working_dir: /workspace
    command: ./scripts/build-and-test.sh --clean
    
  # Memory check runner (requires full dev environment)
  memcheck:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: development
    working_dir: /workspace
    command: ./scripts/build-and-test.sh --clean --memcheck
    environment:
      - TERM=xterm-256color
