[project]
name = "python_practice"
version = "2025.08.27"
requires-python = ">=3.13.7"

[project.scripts]
lis = "concepts.dynamic_programming.dupe_lis:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "pytest-cov",
    "ipython"
]
